version: "3"

services:
    db:
        image: kuuku123/ipl-dashboard:mysql
        container_name: mysql-server
        ports:
                - "3307:3306"
        #environment:
        #- MYSQL_DATABASE=ipl_dashboard
        #- MYSQL_ROOT_PASSWORD=1234
        #- TZ=Asia/Seoul


