version: "3"

services:
    frontend:
        image: kuuku123/skt:frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        container_name: backend
        restart: on-failure
        image: kuuku123/skt:backend
        ports:
            - "8300:8300"
        environment:
            MYSQL_HOST: mysql-server
            MYSQL_PORT: 3306
        depends_on:
            - mysql-server

    db:
        image: kuuku123/skt:mysql
        container_name: mysql-server


